version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: intervume-postgres
    environment:
      POSTGRES_DB: intervume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: intervume-redis
    ports:
      - "6379:6379"

  # Main Application (Backend + Frontend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intervume-app
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/intervume
      - REDIS_URL=redis://redis:6379
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: