version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: intervume-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/node_modules
    command: npm run dev --workspace=@intervume/server-api

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    container_name: intervume-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/ui:/app/packages/ui
      - /app/node_modules
    command: npm run dev --workspace=@intervume/ui-core
    depends_on:
      - backend

 